#ifndef STUFFMANAGEMENT_GLOBAL_H
#define STUFFMANAGEMENT_GLOBAL_H

#include <Qt/qglobal.h>

#ifdef STAFFMANAGEMENT_LIB
# define STAFFMANAGEMENT_EXPORT Q_DECL_EXPORT
#else
# define STAFFMANAGEMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // STUFFMANAGEMENT_GLOBAL_H
