#ifndef STUFFMANAGEMENT_GLOBAL_H
#define STUFFMANAGEMENT_GLOBAL_H

#include <Qt/qglobal.h>

#ifdef STUFFMANAGEMENT_LIB
# define STUFFMANAGEMENT_EXPORT Q_DECL_EXPORT
#else
# define STUFFMANAGEMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // STUFFMANAGEMENT_GLOBAL_H
