///////////////////////////////////////////////////////////
//  messagedef.h
//  Implementation of the messagedef
//  Created on:      08-Apr-2009 10:06:32 AM
//  Original author: Tim Kuo
///////////////////////////////////////////////////////////

#if !defined(EA_9F454DB8_A969_4830_9B7B_1DCC06DF5CD6__INCLUDED_)
#define EA_9F454DB8_A969_4830_9B7B_1DCC06DF5CD6__INCLUDED_

#include "common.h"

#define EventDb (2000)
#define EventNet (3000)
#define EventLocal (4000)


enum MESSAGE_TYPE {
	EVENT = 0,
	ACTION_COMMON = (GROUP_COMMON<<24),
	ACTION_SF_COMMON = (GROUP_STAFFMGNT<<24)
};

enum MESSAGE_STAFFMGNT {
	ACTION_SF_BROWSE = ((ACTION_SF_COMMON | 0x00FF0000) & ((SUBGROUP_SF_STAFFBROWSE<<16) | 0xFF000000)),
	ACTION_SF_INFOMGNT = ((ACTION_SF_COMMON | 0x00FF0000) & ((SUBGROUP_SF_INFOMGNT<<16) | 0xFF000000)),
	ACTION_SF_SALARYMGNT = ((ACTION_SF_COMMON | 0x00FF0000) & ((SUBGROUP_SF_SALARYMGNT<<16) | 0xFF000000)),
	ACTION_SF_PASSWORDMGNT= ((ACTION_SF_COMMON | 0x00FF0000) & ((SUBGROUP_SF_PASSWORDMGNT<<16) | 0xFF000000))
};

//ACTION format: GROUP(high 8 bit) + SUBGROUP(middle 8 bit) + action id(low 16 bit)
enum ACTION{
	ACTION_SYSTEM_START = ACTION_COMMON + 1,
	ACTION_SETSUPERUSER,
	ACTION_LOGIN,
	ACTION_LOGOFF,
	ACTION_EXIT,
	ACTION_MAINMENU,
	ACTION_STAFFMGNT = ACTION_SF_COMMON + 1,
	ACTION_GEALLSTAFF,
	ACTION_CHANGEPASSWORD,
	ACTION_GETSTAFF = ACTION_SF_BROWSE + 1,
	ACTION_ADDSTAFF = ACTION_SF_INFOMGNT + 1,
	ACTION_DELLSTAFF,
	ACTION_MODIFYSTAFF,
	ACTION_RESETPASSWORD,
	ACTION_VIEWSTAFFTASKS = ACTION_SF_SALARYMGNT +1,
	ACTION_VIEWSTAFFSALARY,
	ACTGION_MODIFYSTAFFSALARY,
	ACTION_END
};

enum EVENT{
	EVENT_SYSTEM_START = EVENT +1,
	EVENT_INIT,
	EVENT_INIT_FINISHED,
	EVENT_WIZARD,
	EVENT_LOGGEDIN,
	EVENT_LOGGEDOFF,
	EVENT_EXIT,
	EVENT_MAINMENU,
	EVENT_STAFFMGNT,
	EVENT_ALLSTAFF,
	EVENT_STAFF,
	EVENT_STAFFADDED,
	EVENT_END
};

enum TYPE {
	TYPE_SUPPER = 0,
	TYPE_BOSS,
	TYPE_SHOP_MANAGER,
	TYPE_CASHER,
	TYPE_BARBER,
	TYPE_WASHER,
	TYPE_BEAUTICIAN,
	TYPE_MASSAGER
};

enum LEVEL {
	LEVEL_ROOKIE = 0,
	LEVEL_EXPERIENCED,
	LEVEL_SKILLED,
	LEVEL_ADVANCED,
	LEVEL_MASTER
};

enum SEX {
	SEX_UNDEFINED = 0,
	SEX_MALE,
	SEX_FEMALE
};


#endif // !defined(EA_9F454DB8_A969_4830_9B7B_1DCC06DF5CD6__INCLUDED_)
