#ifndef CHINESESTRINGS_H
#define CHINESESTRINGS_H
//#include "common.h"

//group name
#define smString "员工管理"
#define bmString "业务管理"
#define soString "店面运营"
#define logoffString "注销"
#define exitString "退出"
#define zeroSelectionWarning "您还没有选择选择任何列表项。"

//common strings
#define undefineStr "未定义"
#define scoreStr "分"
#define femaleStr "女"
#define maleStr "男"
#define cosmeticNameStr "Cosmetic（科思美）美容美发业运营系统"
#define emptyStr ""
#define staffEntraceStr "员工入口"
#define passwordStr "密码"
#define LoginStr "登录"
#define idStr "编号"
#define okStr "确定"
#define cancleStr "取消"
#define backStr "返回"
#define expandSideBarStr "展开侧边栏"
#define shrinkSideBarStr "收起侧边栏"
#define sexUndefinedStr "未设定"
#define sexMaleStr "男"
#define sexFemaleStr "女"
#define modifyWaring "未能成功修改，请重试。"
#define abandonModifyWarning "还有未提交的修改信息，放弃修改?"
#define leftMark "“"
#define rightMark "”"
#define removeError "未能成功删除选定项目，请重试。"
#define choosePicStr "选择照片"
#define editStr "编辑"
#define submitStr "提交"
#define imageFileStr "图像文件(*.png *.jpg *.bmp *.gif)"
#define imageSizeWarning "非常抱歉，照片文件大小不能超过%1兆，请重新选择。"
static const char* sexStr[] = { sexUndefinedStr, sexMaleStr, sexFemaleStr };

//common mgnt strings
#define loginWindowTitle "登录错误"
#define loginErrorWarning "工号或密码错误，请重新输入。"

//staff mgnt strings
#define staffIDStr "工号"
#define staffNameStr "姓名"
#define staffSexStr "性别"
#define staffJobStr "职务"
#define staffLevelStr "级别"
#define staffStatusStr "状态"
#define staffRatingStr "客户满意度"
#define staffCellStr "手机"
#define staffPhoneStr "座机"
#define staffAddressStr "地址"
#define staffDescriptionStr "备注"
#define staffJobSalaryStr "职务工资"
#define staffLevelSalaryStr "级别工资"
#define staffProfitStr "提成(%)"
#define staffBrowseStr "员工浏览"
#define staffJobSettingStr "职务设置"
#define staffLevelSettingStr "级别设置"
//***********staff mgnt message box strings
#define smEditModeWarning "目前处于新建员工状态，请完成后再修改资料。"
#define smEmptyNameWarnning "员工姓名不能留空， \n请返回并填写员工姓名。"
#define smRemoveStaffConfirm "确定删除选定员工“%1”？\n如果员工离职，建议您更改该员工状态，而不是在系统中删除该员工。"
#define smAddStaffError "未能成功添加员工，请重试。"
#define smModifyStaffError "未能成功修改员工信息，请重试。"
#define smJobRemoveWarning "未能成功删除，可能是还有员工被设置为该职务。"
#define smLevelRemoveWarning "未能成功删除，可能是还有员工被设置为该等级。"
#define smChangePwSucces "你的密码已经成功更改。"
#define smChangePwFailure "原始密码错误，你的密码未能更改。"

//business mgnt string
#define bmBrandStr "品牌"
#define bmBuysStr "进货"
#define bmCostStr "成本"
#define bmDescriptionStr "描述"
#define bmDiscountStr "折扣"
#define bmIdStr "代码"
#define bmNameStr "名称"
#define bmRatingStr "客户满意度"
#define bmPriceStr "价格"
#define bmSalesStr "总销售"
#define bmSpecificationStr "规格"
#define bmStocksStr "库存"
#define bmTypeStr "业务种类"
#define bmAdjustableStr "手动调整"
#define bmDualDiscountStr "重复折扣"
#define bmBusinessTypeCategoryStr "业务性质"
#define bmBusinessTypeDescriptionStr "描述"
#define bmBusinessTypeNameStr "种类名称"
#define bmBusinessTypeIdStr "代码"
#define bmNonProfitableStr "开销性业务"
#define bmProfitableServiceStr "营利性服务"
#define bmProfitableSaleStr "营利性商品"
#define bmBrowseStr "业务浏览"
#define bmTypeEditorStr "业务种类编辑"
#define bmModifyBusinessErrorStr "未能成功修改业务明细，请重试。"
#define bmAddBusinessErrorStr "未能成功添加新业务，请重试。"
#define bmRemoveBusinessConfirm "业务“%1”及其所有营销纪录都将被清空！\n确定贵公司不再提供该业务？"
static const char*  BusinessCategoryStr[] = {bmNonProfitableStr, bmProfitableServiceStr, bmProfitableSaleStr};

#endif
